apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  ports:
    - port: 80
  selector:
    app: php
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
      tier: frontend
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      containers:
      - image: php-image
        name: php-container
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: php
        volumeMounts:
        - name: php-volume
          mountPath: /var/www/html
      volumes:
      - name: php-volume
        persistentVolumeClaim:
          claimName: php-pv-claim
