---
- name: install web components
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - apache2
    - php
    - php-mysql

- name: ensure apache2 started
  service: name=apache2 state=started  enabled=yes

- name: copy web app files
  copy: src=webapp/ dest=/var/www/html mode=0755
  notify: restart apache2

- name: remove default apache2 landing page
  file: path=/var/www/html/index.html state=absent
  notify: restart apache2

- name: add private ip
  replace:
    path: /var/www/html/config.php
    regexp: '10.0.2.17'
    replace: "{{ private_ip_db }}"
